print("Olá Mundo")
nome = input("Digite um nome: ")
cidade = input("Digite uma cidade: ")
print("Meu nome é ",nome,". Eu sou de ",cidade,".")
n1 = int(input("Digite um numero: "))
n2 = int(input("Digite outro numero: "))
s = n1 + n2
print("A soma de {0} e {1} é {2}.".format(n1, n2, s))
print("O tipo da variável nome é: ",type(nome))
print("O tipo da variável n1 é: ",type(n1))
abc = input("Digite algo: ")
print("É alfanumperico? ",abc.isalnum())
print("É numérico?",abc.isnumeric())
print("É alfabético?",abc.isalpha())
print("Está em maiúsculas?",abc.isupper())
print("Está em minúsculas?",abc.islower())
print("É decimal?",abc.isdecimal())
print("Está capitalizada?",abc.istitle())